In [4]:
import torch as th
import torch.nn as nn
import torch.nn.functional as F
import syft as sy

hook = sy.TorchHook(th)

alice = sy.VirtualWorker(hook, id="alice")
bob = sy.VirtualWorker(hook, id="bob")
charlie = sy.VirtualWorker(hook, id="charlie")
dan = sy.VirtualWorker(hook, id="dan")
james = dan

hook.local_worker.is_client_worker = False
me = hook.local_worker
from syft.generic.pointers.pointer_plan import PointerPlan

import sys
torch = th
syft = sy
#print(sy.hook.local_worker.get_worker('alice')._objects)

In [5]:
x = th.tensor([4.2])

In [6]:
x.send(bob)

(32, (2, (13, (92434762338, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\x00storageq\x01ctorch\nFloatStorage\nq\x02X\x0f\x00\x00\x00140455363344384q\x03X\x03\x00\x00\x00cpuq\x04K\x01Ntq\x05QK\x00K\x01\x85q\x06K\x01\x85q\x07\x89ccollections\nOrderedDict\nq\x08)Rq\ttq\nRq\x0b.\x80\x02]q\x00X\x0f\x00\x00\x00140455363344384q\x01a.\x01\x00\x00\x00\x00\x00\x00\x00ff\x86@', None, None, None, None))))
None


(Wrapper)>[PointerTensor | me:61531830563 -> bob:92434762338]

In [8]:
(32, (2, (13, (92434762338, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\x00storageq\x01ctorch\nFloatStorage\nq\x02X\x0f\x00\x00\x00140455363344384q\x03X\x03\x00\x00\x00cpuq\x04K\x01Ntq\x05QK\x00K\x01\x85q\x06K\x01\x85q\x07\x89ccollections\nOrderedDict\nq\x08)Rq\ttq\nRq\x0b.\x80\x02]q\x00X\x0f\x00\x00\x00140455363344384q\x01a.\x01\x00\x00\x00\x00\x00\x00\x00ff\x86@', None, None, None, None))))

(32,
 (2,
  (13,
   (92434762338,
    b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\x00storageq\x01ctorch\nFloatStorage\nq\x02X\x0f\x00\x00\x00140455363344384q\x03X\x03\x00\x00\x00cpuq\x04K\x01Ntq\x05QK\x00K\x01\x85q\x06K\x01\x85q\x07\x89ccollections\nOrderedDict\nq\x08)Rq\ttq\nRq\x0b.\x80\x02]q\x00X\x0f\x00\x00\x00140455363344384q\x01a.\x01\x00\x00\x00\x00\x00\x00\x00ff\x86@',
    None,
    None,
    None,
    None))))

In [3]:
from syft.messaging.message import Message

In [14]:
from syft.serde.serde import simplifiers

In [15]:
simplifiers

OrderedDict([(dict,
              (0,
               <function syft.serde.native_serde._simplify_dictionary(my_dict: Dict) -> Tuple>)),
             (list,
              (1,
               <function syft.serde.native_serde._simplify_collection(my_collection: Collection) -> Tuple>)),
             (range,
              (2,
               <function syft.serde.native_serde._simplify_range(my_range: range) -> Tuple[int, int, int]>)),
             (set,
              (3,
               <function syft.serde.native_serde._simplify_collection(my_collection: Collection) -> Tuple>)),
             (slice,
              (4,
               <function syft.serde.native_serde._simplify_slice(my_slice: slice) -> Tuple[int, int, int]>)),
             (str,
              (5,
               <function syft.serde.native_serde._simplify_str(obj: str) -> tuple>)),
             (tuple,
              (6,
               <function syft.serde.native_serde._simplify_collection(my_collection: Collection) -> Tuple>)),

In [20]:
@sy.func2plan(args_shape=[(1,)], state=(th.tensor([4.2]),))
def plan(x, state):
    bias, = state.read()
    x = x.abs()
    return x + bias

(32, (2, (13, (4761953181, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\x00storageq\x01ctorch\nFloatStorage\nq\x02X\x0f\x00\x00\x00140455365502960q\x03X\x03\x00\x00\x00cpuq\x04K\x01Ntq\x05QK\x00K\x01\x85q\x06K\x01\x85q\x07\x89ccollections\nOrderedDict\nq\x08)Rq\ttq\nRq\x0b.\x80\x02]q\x00X\x0f\x00\x00\x00140455365502960q\x01a.\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', None, None, None, None))))
None
(32, (2, (13, (79291281735, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x

In [24]:
isinstance(b'__add__', bytearray)

False

In [22]:
ptr_plan = plan.send(alice, bob)
ptr_plan

(32, (2, (19, (72165846784, (21, (((31, (1, ((6, ((5, (b'abs',)), (23, (26907042306, 4761953181, 'alice', None, (10, (1,)), True)), (6, ()), (0, ()))), (48699021648,)))), (31, (1, ((6, ((5, (b'__add__',)), (23, (69709419596, 48699021648, 'alice', None, None, True)), (6, ((23, (74656180278, 79291281735, 'alice', None, (10, (1,)), False)),)), (0, ()))), (83495087450,))))), (6, (4761953181,)), (6, (83495087450,)))), (20, ((1, (79291281735,)), (1, ((13, (79291281735, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\x00storageq\x01ctorch\nFloatStorage\nq\x02X\x0f\x00\x00\x00140455350011776q\x03X\x03\x00\x00\x00cpuq\x04K\x01Ntq\x05QK\x00K\x01\x85q\x06K\x01\x85q\x07\x89ccollections\nOrderedD

[PointerPlan | me:55894304374
	 -> alice:72165846784
	 -> bob:72165846784
]

In [4]:
fetched_plan = plan.owner.fetch_plan(ptr_plan.id_at_location, james)

(38, (10, ((5, (b'fetch_plan',)), (6, (57895708650, False)))))
(19, (57895708650, (21, (((31, (1, ((6, ((5, (b'abs',)), (23, (25208484331, 51684948173, b'dan', None, (10, (1,)), True)), (6, ()), (0, ()))), (62869536441,)))), (31, (1, ((6, ((5, (b'__add__',)), (23, (9655331350, 62869536441, b'dan', None, None, True)), (6, ((23, (89426198911, 4863941835, b'dan', None, (10, (1,)), False)),)), (0, ()))), (3263650475,))))), (6, (51684948173,)), (6, (3263650475,)))), (20, ((1, (4863941835,)), (1, ((13, (4863941835, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\x00storageq\x01ctorch\nFloatStorage\nq\x02X\x0f\x00\x00\x00140400015244496q\x03X\x03\x00\x00\x00cpuq\x04K\x01Ntq\x05QK\x00K\x01\x

In [6]:
(38, (10, ((5, (b'fetch_plan',)), (6, (57895708650, False)))))
(19, (57895708650, (21, (((31, (1, ((6, ((5, (b'abs',)), (23, (25208484331, 51684948173, b'dan', None, (10, (1,)), True)), (6, ()), (0, ()))), (62869536441,)))), (31, (1, ((6, ((5, (b'__add__',)), (23, (9655331350, 62869536441, b'dan', None, None, True)), (6, ((23, (89426198911, 4863941835, b'dan', None, (10, (1,)), False)),)), (0, ()))), (3263650475,))))), (6, (51684948173,)), (6, (3263650475,)))), (20, ((1, (4863941835,)), (1, ((13, (4863941835, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\x00storageq\x01ctorch\nFloatStorage\nq\x02X\x0f\x00\x00\x00140400015244496q\x03X\x03\x00\x00\x00cpuq\x04K\x01Ntq\x05QK\x00K\x01\x85q\x06K\x01\x85q\x07\x89ccollections\nOrderedDict\nq\x08)Rq\ttq\nRq\x0b.\x80\x02]q\x00X\x0f\x00\x00\x00140400015244496q\x01a.\x01\x00\x00\x00\x00\x00\x00\x00ff\x86@', None, None, None, None)),)))), True, True, (5, (b'plan',)), None, None))

(19,
 (57895708650,
  (21,
   (((31,
      (1,
       ((6,
         ((5, (b'abs',)),
          (23, (25208484331, 51684948173, b'dan', None, (10, (1,)), True)),
          (6, ()),
          (0, ()))),
        (62869536441,)))),
     (31,
      (1,
       ((6,
         ((5, (b'__add__',)),
          (23, (9655331350, 62869536441, b'dan', None, None, True)),
          (6,
           ((23,
             (89426198911, 4863941835, b'dan', None, (10, (1,)), False)),)),
          (0, ()))),
        (3263650475,))))),
    (6, (51684948173,)),
    (6, (3263650475,)))),
  (20,
   ((1, (4863941835,)),
    (1,
     ((13,
       (4863941835,
        b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\

In [5]:
(19, (57895708650, (21, (((31, (1, ((6, ((5, (b'abs',)), (23, (25208484331, 51684948173, b'dan', None, (10, (1,)), True)), (6, ()), (0, ()))), (62869536441,)))), (31, (1, ((6, ((5, (b'__add__',)), (23, (9655331350, 62869536441, b'dan', None, None, True)), (6, ((23, (89426198911, 4863941835, b'dan', None, (10, (1,)), False)),)), (0, ()))), (3263650475,))))), (6, (51684948173,)), (6, (3263650475,)))), (20, ((1, (4863941835,)), (1, ((13, (4863941835, b'binary_tensor_data', None, None, None, None)),)))), True, True, (5, (b'plan',)), None, None))

(19,
 (57895708650,
  (21,
   (((31,
      (1,
       ((6,
         ((5, (b'abs',)),
          (23, (25208484331, 51684948173, b'dan', None, (10, (1,)), True)),
          (6, ()),
          (0, ()))),
        (62869536441,)))),
     (31,
      (1,
       ((6,
         ((5, (b'__add__',)),
          (23, (9655331350, 62869536441, b'dan', None, None, True)),
          (6,
           ((23,
             (89426198911, 4863941835, b'dan', None, (10, (1,)), False)),)),
          (0, ()))),
        (3263650475,))))),
    (6, (51684948173,)),
    (6, (3263650475,)))),
  (20,
   ((1, (4863941835,)),
    (1,
     ((13, (4863941835, b'binary_tensor_data', None, None, None, None)),)))),
  True,
  True,
  (5, (b'plan',)),
  None,
  None))

In [ ]:
(19, (57895708650, (21, (((31, (1, ((6, ((5, (b'abs',)), (23, (25208484331, 51684948173, b'dan', None, (10, (1,)), True)), (6, ()), (0, ()))), (62869536441,)))), (31, (1, ((6, ((5, (b'__add__',)), (23, (9655331350, 62869536441, b'dan', None, None, True)))), )))), (6, (51684948173,)), (6, (3263650475,)))), (20, ((1, (4863941835,)), (1, ((13, (4863941835, b'binary_tensor_data', None, None, None, None)),)))), True, True, (5, (b'plan',)), None, None))

In [5]:
@sy.func2plan(args_shape=[(1,)], state={"bias": 1.})
def plan(x, state):
    bias = state.read("bias")
    x = x.abs()
    return x + bias


 (32, (2, (13, (75049840459, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\x00storageq\x01ctorch\nFloatStorage\nq\x02X\x0f\x00\x00\x00140398958018944q\x03X\x03\x00\x00\x00cpuq\x04K\x01Ntq\x05QK\x00K\x01\x85q\x06K\x01\x85q\x07\x89ccollections\nOrderedDict\nq\x08)Rq\ttq\nRq\x0b.\x80\x02]q\x00X\x0f\x00\x00\x00140398958018944q\x01a.\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', None, None, None, None))))

 None

 (31, (1, ((6, ((5, (b'abs',)), (23, (6219287291, 75049840459, 76624135880, None, (10, (1,)), True)), (6, ()), (0, ()))), (67543886710,))))

 None

 (31, (1, ((6, ((5, (b'__add__',)), (23, (13387269616, 67543886710, 76624135880, None, None, True)), (6, (1.0,)), (0, ()))), 

In [6]:
ptr_plan = plan.send(james)


 (32, (2, (19, (76624135880, (21, (((31, (1, ((6, ((5, (b'abs',)), (23, (6219287291, 75049840459, 'dan', None, (10, (1,)), True)), (6, ()), (0, ()))), (67543886710,)))), (31, (1, ((6, ((5, (b'__add__',)), (23, (13387269616, 67543886710, 'dan', None, None, True)), (6, (1.0,)), (0, ()))), (89151963699,))))), (6, (75049840459,)), (6, (89151963699,)))), (20, ((1, ()), (1, ()))), True, True, (5, (b'plan',)), None, None))))

 None


In [7]:
fetched_plan = plan.owner.fetch_plan(ptr_plan.id_at_location, james)


 (38, (10, ((5, (b'fetch_plan',)), (6, (76624135880, False)))))

 (19, (76624135880, (21, (((31, (1, ((6, ((5, (b'abs',)), (23, (6219287291, 75049840459, b'dan', None, (10, (1,)), True)), (6, ()), (0, ()))), (67543886710,)))), (31, (1, ((6, ((5, (b'__add__',)), (23, (13387269616, 67543886710, b'dan', None, None, True)), (6, (1.0,)), (0, ()))), (89151963699,))))), (6, (75049840459,)), (6, (89151963699,)))), (20, ((1, ()), (1, ()))), True, True, (5, (b'plan',)), None, None))


In [2]:
alice.clear_objects()
bob.clear_objects()
charlie.clear_objects()
dan.clear_objects()
me.clear_objects()

<VirtualWorker id:me #objects:0>

In [3]:
@sy.func2plan(args_shape=[(1,)], state={"bias": th.tensor([1])})
def plan_abs(x, state):
    bias = state.read("bias")
    x = x.abs()
    return x + bias

plan_ptr = plan_abs.send(bob)
x_ptr = th.tensor([-1, 7, 3]).send(bob)
print(plan_ptr)
p = plan_ptr(x_ptr)
x_abs = p.get()
assert (x_abs == th.tensor([2, 8, 4])).all()

x_ptr = th.tensor([-1, 9, 3]).send(alice)
p = plan_ptr(x_ptr)
x_abs = p.get()
assert (x_abs == th.tensor([2, 10, 4])).all()

[PointerPlan | me:81687599853 -> bob:55135370543]


KeyError: 'Object "7592351841" not found on worker!!!You just tried to interact with an object ID:7592351841 on <VirtualWorker id:bob #objects:4> which does not exist!!! Use .send() and .get() on all your tensors to make sure they\'reon the same machines. If you think this tensor does exist, check the ._objects dictionaryon the worker and see for yourself!!! The most common reason this error happens is because someone calls.get() on the object\'s pointer without realizing it (which deletes the remote object and sends it to the pointer). Check your code to make sure you haven\'t already called .get() on this pointer!!!'

In [3]:
@sy.func2plan(args_shape=[(1,)])
def plan_abs(data):
    return data.abs()

plan_ptr = plan_abs.send(bob, alice)
x_ptr = th.tensor([-1, 7, 3]).send(bob)
p = plan_ptr(x_ptr)
print(p)
x_abs = p.get()
assert (x_abs == th.tensor([1, 7, 3])).all()

x_ptr = th.tensor([-1, 9, 3]).send(alice)
p = plan_ptr(x_ptr)
x_abs = p.get()
assert (x_abs == th.tensor([1, 9, 3])).all()

(Wrapper)>[PointerTensor | me:81450360692 -> bob:60069576960]


In [4]:
a = b = c = 2
b, c, a

(2, 2, 2)

In [5]:
alice.clear_objects()
x = th.tensor([1.2]).fix_precision().share(alice, bob, crypto_provider=charlie)

def f(x):
    print(x.id, x.owner, x.child.id, x.child.owner, x.child.child.id, x.child.child.owner)
    xc = x.clone()
    print(xc.id, xc.owner, xc.child.id, xc.child.owner, xc.child.child.id, xc.child.child.owner)
    return xc

xc = f(x)
print(alice._objects)
xc.get().float_prec()

89652066803 <VirtualWorker id:me #objects:26> 89652066803 <VirtualWorker id:me #objects:26> 35510113435 <VirtualWorker id:me #objects:26>
89652066803 <VirtualWorker id:me #objects:26> 89652066803 <VirtualWorker id:me #objects:26> 35510113435 <VirtualWorker id:me #objects:26>
{47184758592: tensor([488679289287760022])}


tensor([1.2000])

In [4]:
is_func2plan=True
if is_func2plan:

    @sy.func2plan(args_shape=[(1,)], state={"bias": th.tensor([3.0])})
    def plan(data, state):
        bias = state.read("bias")
        return data * bias

else:

    class Net(sy.Plan):
        def __init__(self):
            super(Net, self).__init__()
            self.fc1 = nn.Linear(1, 1)

        def forward(self, x):
            return self.fc1(x)

    plan = Net()
    plan.build(th.tensor([1.2]))

plan_pointer = plan.fix_precision().share(alice, bob, crypto_provider=charlie).send(james)

In [5]:
james._objects

{6048816592: (Wrapper)>FixedPrecisionTensor>[AdditiveSharingTensor]
 	-> [PointerTensor | dan:42695256424 -> alice:12851285675]
 	-> [PointerTensor | dan:41809528293 -> bob:57767771314]
 	*crypto provider: charlie*,
 41621367669: <Plan plan id:41621367669 owner:dan built>}

In [6]:
state_ids = james._objects[plan.id].state.state_ids
state_ids

[6048816592]

In [7]:
tensor = james._objects[state_ids[0]]
tensor.id, tensor

(6048816592, (Wrapper)>FixedPrecisionTensor>[AdditiveSharingTensor]
 	-> [PointerTensor | dan:42695256424 -> alice:12851285675]
 	-> [PointerTensor | dan:41809528293 -> bob:57767771314]
 	*crypto provider: charlie*)

In [8]:
fetched_plan = plan_pointer.owner.fetch_plan(plan_pointer.id_at_location, james, copy=True)

In [18]:
t = torch.tensor([1, 2])
crt = t.fix_precision(field_type="int100", precision_fractional=2, storage="crt")

to_alice = crt.send(alice)
to_alice_id = to_alice.id_at_location

assert to_alice_id in alice._objects

to_bob_to_alice = to_alice.send(bob)
to_bob_to_alice_id = to_bob_to_alice.id_at_location

assert to_alice_id in alice._objects
assert to_bob_to_alice_id in bob._objects

to_alice_back = to_bob_to_alice.get()

assert to_bob_to_alice_id not in bob._objects
assert to_alice_id in alice._objects

t_back = to_alice_back.get()

assert to_alice_id not in alice._objects

print(t_back)
print(crt)
eq = (t_back == crt).float_precision()
assert (eq == torch.tensor([1.0, 1.0])).all()

(Wrapper)>[CRTPrecisionTensor]
	 -> 1201: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1433: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1217: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1237: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1321: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1103: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1129: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1367: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1093: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1039: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
(Wrapper)>[CRTPrecisionTensor]
	 -> 1201: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1433: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1217: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1237: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1321: (Wrapper)>FixedPrecisionTensor>tensor([100, 200])
	 -> 1103: (Wrapper)>Fi

In [5]:
x = th.tensor([-1.0])
x_sh = x.fix_precision().share(alice, bob, crypto_provider=charlie)
x_sh

clone> 66729189993
clone< 66729189993
register at 3984857994 (Wrapper)>FixedPrecisionTensor>tensor([4611686018427386904]) where empty
register at 81202324397 (Wrapper)>tensor([4611686018427386904]) where empty
register at 72652447018 (Wrapper)>FixedPrecisionTensor>[AdditiveSharingTensor]
	-> [PointerTensor | me:79531369700 -> alice:1196459778]
	-> [PointerTensor | me:23340961389 -> bob:78692482375]
	*crypto provider: charlie* where empty


(Wrapper)>FixedPrecisionTensor>[AdditiveSharingTensor]
	-> [PointerTensor | me:79531369700 -> alice:1196459778]
	-> [PointerTensor | me:23340961389 -> bob:78692482375]
	*crypto provider: charlie*

In [6]:
x_sh.clone()

clone> 72652447018
register at 83642647197 (Wrapper)>tensor([0.]) where empty
clone< 11463460143


(Wrapper)>FixedPrecisionTensor>[AdditiveSharingTensor]
	-> [PointerTensor | me:9511912212 -> alice:66991310238]
	-> [PointerTensor | me:89176795039 -> bob:46153768481]
	*crypto provider: charlie*

In [18]:
class Net(sy.Plan):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(1, 1)

    def forward(self, x):
        return self.fc1(x)

plan = Net()
plan.build(th.tensor([1.2]))
    
plan.fix_precision().share(alice, bob, crypto_provider=charlie)


ptr_plan = plan.send(james)

# Fetch plan
fetched_plan = a(ptr_plan.id_at_location, james)


# Execute the fetch plan
x = th.tensor([-1.0])
x_sh = x.fix_precision().share(alice, bob, crypto_provider=charlie)
result = fetched_plan(x_sh)
decrypted = result.get().float_prec()

# Compare with local plan
plan.get()
plan.float_precision()
x = th.tensor([-1.0])
print('===')
print(plan.fc1.weight)

register at 1877891315 (Wrapper)>[PointerTensor | me:1877891315 -> 42938962171:57589981849] where empty
register at 7481811826 (Wrapper)>[PointerTensor | me:7481811826 -> 42938962171:91709737234] where empty
id 44236753458
id 44236753458
id 35703833413
id 35703833413
register at 70755656844 (Wrapper)>tensor([[887]]) where empty
register at 70755656844 (Wrapper)>[AdditiveSharingTensor]
	-> [PointerTensor | me:93942095022 -> alice:30339481673]
	-> [PointerTensor | me:40751998353 -> bob:28399856703]
	*crypto provider: charlie* where (Wrapper)>[AdditiveSharingTensor]
	-> [PointerTensor | me:93942095022 -> alice:30339481673]
	-> [PointerTensor | me:40751998353 -> bob:28399856703]
	*crypto provider: charlie*
register at 77852530424 (Wrapper)>tensor([4611686018427387293]) where empty
register at 77852530424 (Wrapper)>[AdditiveSharingTensor]
	-> [PointerTensor | me:8598158522 -> alice:10441105603]
	-> [PointerTensor | me:56536484588 -> bob:9551109060]
	*crypto provider: charlie* where (Wrapper

In [3]:
is_func2plan = False

In [12]:
if is_func2plan:

    @sy.func2plan(args_shape=[(1,)], state={"bias": th.tensor([3.0])})
    def plan(data, state):
        bias = state.read("bias")
        return data * bias

else:

    class Net(sy.Plan):
        def __init__(self):
            super(Net, self).__init__()
            self.fc1 = nn.Linear(1, 1)

        def forward(self, x):
            print('Forward', x, self.fc1.bias)
            return self.fc1(x)

    plan = Net()
    plan.build(th.tensor([1.2]))

plan.fix_precision().share(alice, bob, crypto_provider=charlie)


ptr_plan = plan.send(james)

# Fetch plan
fetched_plan = plan.owner.fetch_plan(ptr_plan.id_at_location, james)


# Execute the fetch plan
x = th.tensor([-1.0])
x_sh = x.fix_precision().share(alice, bob, crypto_provider=charlie)
result = fetched_plan(x_sh)
decrypted = result.get().float_prec()

# Compare with local plan
plan.get()
plan.float_precision()
x = th.tensor([-1.0])
print('===')
print(plan.fc1.weight)
expected = plan(x)
assert th.all(decrypted - expected.detach() < 1e-2)
# assert fetched_plan.state.state_ids != plan.state.state_ids #TODO

# Make sure fetched_plan is using the readable_plan
assert fetched_plan.forward is None
assert fetched_plan.is_built

# Make sure plan is using the blueprint: forward
assert plan.forward is not None

register at 27134786911 (Wrapper)>[PointerTensor | me:27134786911 -> 13395450242:69773591621] where empty
Forward (Wrapper)>[PointerTensor | me:27134786911 -> 13395450242:69773591621] (Wrapper)>[PointerTensor | me:55065245503 -> 13395450242:38244555299]
register at 53412873828 (Wrapper)>[PointerTensor | me:53412873828 -> 13395450242:19151945245] where empty
id 79424336584
id 79424336584
id 38244555299
id 38244555299
register at 4335107448 (Wrapper)>tensor([[338]]) where empty
register at 4335107448 (Wrapper)>[AdditiveSharingTensor]
	-> [PointerTensor | me:97803861412 -> alice:45180580120]
	-> [PointerTensor | me:83607462488 -> bob:67081857389]
	*crypto provider: charlie* where (Wrapper)>[AdditiveSharingTensor]
	-> [PointerTensor | me:97803861412 -> alice:45180580120]
	-> [PointerTensor | me:83607462488 -> bob:67081857389]
	*crypto provider: charlie*
register at 43143683546 (Wrapper)>tensor([266]) where empty
register at 43143683546 (Wrapper)>[AdditiveSharingTensor]
	-> [PointerTensor |

KeyError: 'Object "45180580120" not found on worker!!!You just tried to interact with an object ID:45180580120 on <VirtualWorker id:alice #objects:44> which does not exist!!! Use .send() and .get() on all your tensors to make sure they\'reon the same machines. If you think this tensor does exist, check the ._objects dictionaryon the worker and see for yourself!!! The most common reason this error happens is because someone calls.get() on the object\'s pointer without realizing it (which deletes the remote object and sends it to the pointer). Check your code to make sure you haven\'t already called .get() on this pointer!!!'

In [3]:
x = th.tensor([-1.0])
print(x.id)
x.fix_precision_()
print(x.id)
x.share_(alice, bob, crypto_provider=charlie)
print(x.id)

80339099253
id 80339099253
id 80339099253
80339099253
80339099253


In [6]:
x = th.tensor([-1.0])
x.fix_precision_().share_(alice, bob, crypto_provider=charlie)
print(x)
x.get_().float_precision_()
print(x)

meth arg tensor([-1.])
Tensor>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
	-> [PointerTensor | me:72721408490 -> alice:17319977397]
	-> [PointerTensor | me:30576794046 -> bob:21503752519]
	*crypto provider: charlie*
tensor([-1.])


In [5]:
x = th.tensor([-1.0])
x_sh = x.fix_precision().share(alice, bob, crypto_provider=charlie)

meth arg tensor([-1.])
id set at 25166120385 : 25166120385


In [6]:
x_sh.clone()

meth arg (Wrapper)>FixedPrecisionTensor>[AdditiveSharingTensor]
	-> [PointerTensor | me:6480982762 -> alice:18760437809]
	-> [PointerTensor | me:19191973230 -> bob:60456761549]
	*crypto provider: charlie*
id set at 92216924999 : 92216924999


tensor([])

In [15]:
res = plan(th.tensor([1.0]))

bias tensor([3.])


In [6]:
res

tensor([3.])

In [7]:
ptr_plan = plan.send(alice)

simplify [tensor([3.])]


In [9]:
p = th.tensor([2.0]).send(alice)
p

(Wrapper)>[PointerTensor | me:10755526900 -> alice:81168473358]

In [10]:
ptr_plan(p).get()

tensor([6.])

In [20]:
@sy.func2plan(args_shape=[(1,)], state={"bias": th.tensor([3.0])})
def plan(data, state):
    bias = state.read("bias")
    return data * bias

ptr_plan = plan.send(alice)

plan.get()

[(31, (1, ((6, ((5, (b'__mul__',)), (23, (35713076843, 12275943928, 'me', None, (10, (1,)), True)), (6, ((23, (92917339826, 56915725177, 'me', None, (10, (1,)), True)),)), (0, ()))), (17100190141,))))]
* [56915725177]
ptr tensor([3.])


AttributeError: 'Tensor' object has no attribute 'child'

In [19]:
x_sh = th.tensor([3.0]).fix_precision()#.share(alice, bob, crypto_provider=charlie)

In [20]:
x_sh.float_prec_() == th.tensor([3.0])

tensor([1], dtype=torch.uint8)

In [14]:
me.get_obj(57192922242)

(Wrapper)>FixedPrecisionTensor>tensor([4611686018427386904])

In [11]:
me.get_obj(84112600942)

tensor([3.])

In [7]:
plan.commands.arg_ids

[68519530406]

In [8]:
plan.commands.result_ids

(75165665059,)

In [9]:
alice._objects

{}

In [6]:
rplan = alice.get_obj(48869846473)

In [7]:
rplan.bias

tensor([2.])

In [15]:
plan.bias

tensor([2.])

In [8]:
hook.local_worker.is_client_worker = False

@sy.func2plan(args_shape=[(1,)], state={"bias": th.tensor([2.0])})
def plan(x, state):
    bias = state.read("bias")
    return x + bias

plan.send(alice)

hook.local_worker.clear_objects()

# Fetch plan
fetched_plan = plan.owner.fetch_plan(plan.id, alice)

print(hook.local_worker._objects)
print(fetched_plan)
print(fetched_plan.state.state_ids)
print(fetched_plan.commands.arg_ids)
print(fetched_plan.readable_plan)
# Execute it locally
x = th.tensor([-1.0])
print(fetched_plan(x))

hook.local_worker.is_client_worker = True

state tupele (20, ((1, ((5, (b'bias',)),)), (1, (50428538245,)), (1, ((13, (1674357582, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\x00little_endianq\x02\x88X\n\x00\x00\x00type_sizesq\x03}q\x04(X\x05\x00\x00\x00shortq\x05K\x02X\x03\x00\x00\x00intq\x06K\x04X\x04\x00\x00\x00longq\x07K\x04uu.\x80\x02ctorch._utils\n_rebuild_tensor_v2\nq\x00((X\x07\x00\x00\x00storageq\x01ctorch\nFloatStorage\nq\x02X\x0f\x00\x00\x00140419995499696q\x03X\x03\x00\x00\x00cpuq\x04K\x01Ntq\x05QK\x00K\x01\x85q\x06K\x01\x85q\x07\x89ccollections\nOrderedDict\nq\x08)Rq\ttq\nRq\x0b.\x80\x02]q\x00X\x0f\x00\x00\x00140419995499696q\x01a.\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@', None, None, None, None)),))))
state tupele (20, ((1, ((5, (b'bias',)),)), (1, (50428538245,)), (1, ((13, (50428538245, b'\x80\x02\x8a\nl\xfc\x9cF\xf9 j\xa8P\x19.\x80\x02M\xe9\x03.\x80\x02}q\x00(X\x10\x00\x00\x00protocol_versionq\x01M\xe9\x03X\r\x00\x00\

In [2]:
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [3]:
@sy.func2plan(args_shape=[(1,)], state={"bias": th.tensor([2.0])})
def plan(x, state):
    bias = state.read("bias")
    return x + bias


In [4]:
plan.commands.commands

[(31,
  (1,
   ((6,
     ((5, (b'__add__',)),
      (23, (20678530031, 73920391858, 'me', None, (10, (1,)), True)),
      (6, ((23, (86948992756, 451532547, 'me', None, (10, (1,)), True)),)),
      (0, ()))),
    (63415937032,))))]

In [5]:
ptr_plan = plan.send(alice)

state_elements [tensor([2.])]


In [6]:
alice._objects

{451532547: tensor([2.]),
 52376384404: <Plan plan id:52376384404 owner:alice built>}

In [7]:
ptr_plan

[PointerPlan | me:37703660786 -> alice:52376384404]

In [8]:
alice.get_obj(ptr_plan.id_at_location).state.state_ids

[451532547]

In [9]:
alice.get_obj(ptr_plan.id_at_location).commands.arg_ids

[73920391858]

In [10]:
alice.get_obj(ptr_plan.id_at_location).commands.commands

[(31,
  (1,
   ((6,
     ((5, (b'__add__',)),
      (23, (20678530031, 73920391858, b'alice', None, (10, (1,)), True)),
      (6, ((23, (86948992756, 451532547, b'alice', None, (10, (1,)), True)),)),
      (0, ()))),
    (63415937032,))))]

In [11]:
x = th.tensor([1.]).send(alice)
p = ptr_plan(x)
p

Run plan 52376384404@alice isbuilt=True > 3504548155
====> {451532547: tensor([2.]), 52376384404: <Plan plan id:52376384404 owner:alice built>, 47779633425: tensor([1.]), 3504548155: tensor([3.])}
tensor([3.])


(Wrapper)>[PointerTensor | me:91236084300 -> alice:3504548155]

In [12]:
x.id_at_location

47779633425

In [13]:
alice._objects

{451532547: tensor([2.]),
 52376384404: <Plan plan id:52376384404 owner:alice built>,
 47779633425: tensor([1.]),
 3504548155: tensor([3.])}

In [14]:
p.get()

tensor([3.])

In [15]:
@sy.func2plan(args_shape=[(1,)], state={"bias": th.tensor([1.0])})
def plan(x, state):
    bias = state.read("bias")
    return x + bias

plan.send(alice)
id_at_location = plan.id
plan_ptr = me.request_search([id_at_location], location=alice)

plan = plan_ptr.get()

assert isinstance(plan, sy.Plan)

x = th.tensor([1.])
ptr = plan(x)

assert (ptr == th.tensor([2.])).all()

state_elements [tensor([1.])]


TypeError: create_pointer() missing 2 required positional arguments: 'location' and 'id_at_location'

In [5]:
@sy.func2plan(args_shape=[(1,)], state={"bias": th.tensor([1.0])})
def plan(x, state):
    bias = state.read("bias")
    return x + bias

plan.send(alice)
id_at_location = plan.id
plan_ptr = me.request_search([id_at_location], location=alice)

plan = plan_ptr.get()

assert isinstance(plan, sy.Plan)

x = th.tensor([1.])
ptr = plan(x)

assert (ptr == th.tensor([2.])).all()

launching search on alice
_execute_readable_plan
[(29, (1, ((6, ((5, (b'__add__',)), (21, (67997223344, 77129528307, b'me', None, (10, (1,)), True)), (6, ((21, (84086339677, 96055867121, b'me', None, (10, (1,)), True)),)), (0, ()))), (15772215888,))))]


In [3]:
inc1.send(alice)
id_at_location = inc1.id

In [4]:
alice._objects

{20803918614: tensor([1.]),
 96844798724: <Plan inc1 id:96844798724 owner:alice built>}

In [5]:
plan_ptr = sy.PointerPlan(location=alice, id_at_location=id_at_location)

In [6]:
plan_ptr

[PointerPlan | me:2841533489 -> alice:96844798724]

In [7]:
#plan_back = plan_ptr.get()
#x = th.tensor([1.])
#plan_back(x)

In [8]:
x = th.tensor([1.]).send(alice)
plan_ptr(x).get()

request_execute_plan alice 96844798724
[(27, (1, ((6, ((5, (b'__add__',)), (21, (71428670646, 39134698967, b'alice', None, (10, (1,)), True)), (6, ((21, (5364783957, 20803918614, b'alice', None, (10, (1,)), True)),)), (0, ()))), (83786627432,))))]


tensor([2.])

In [ ]:
@sy.func2plan(args_shape=[(1,)], state={"bias": th.tensor([1.0])})
def plan(x, state):
    bias = state.read("bias")
    return x + bias

plan.send(alice)
id_at_location = plan.id

plan_ptr = PointerPlan(location=alice, id_at_location=id_at_location)

x = th.tensor([1.]).send(alice)

ptr = plan_ptr(x)

assert (ptr.get() == th.tensor([2.])).all()