In [1]:
import torch as th
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import syft as sy
#from syft.frameworks.torch.crypto.securenn import relu_deriv, private_compare, relu, decompose, share_convert
sy.create_sandbox(globals(), verbose=False, download_data=False)
import torch
import syft
james = jason
secure_worker = jason

Setting up Sandbox...
Done!


In [6]:
x = torch.tensor([1., 2., 3, 4, 5]).send(alice).share(alice, bob, crypto_provider=james)

In [8]:
x.get()

(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:13305886213 -> alice:8265658545]
	-> (Wrapper)>[PointerTensor | me:27991123829 -> bob:78314637966]
	*crypto provider: jason*

In [2]:
x = torch.tensor([1., 2., 3, 4, 5])
index = torch.tensor([-1.])

torch.roll(x, index)

nem
-1


tensor([2., 3., 4., 5., 1.])

In [5]:
x = torch.tensor([1., 2., 3, 4, 5]).fix_prec(precision_fractional=0).share(alice, bob, crypto_provider=james).child.child.child
index = torch.tensor([-1]).send(alice, bob).child


torch.roll(x, index).get()

[MultiPointerTensor]
	-> (Wrapper)>[PointerTensor | me:46982337954 -> alice:97124698974]
	-> (Wrapper)>[PointerTensor | me:48548948497 -> bob:18659076173]
* torch.roll
tensor([1, 2, 3, 4, 5])
nem
-1
nem
-1
{'alice': (Wrapper)>[PointerTensor | me:21058161882 -> alice:74681155688], 'bob': (Wrapper)>[PointerTensor | me:93708475192 -> bob:92528777516]}
tensor([2, 3, 4, 5, 1])


tensor([2, 3, 4, 5, 1])

In [1]:
import torch

In [5]:
x = torch.tensor([1., 2, 3])
print(x.shape)
torch.zeros(3, 10).scatter(1, x.long(), x)

torch.Size([3])


RuntimeError: invalid argument 3: Index tensor must be either empty or have same dimensions as output tensor at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:470

In [14]:

batch_size = 5
nb_digits = 10
# Dummy input that HAS to be 2D for the scatter (you can use view(-1,1) if needed)
y = torch.FloatTensor(batch_size).random_() % nb_digits

y_onehot = torch.zeros(*y.shape, 10)
y_onehot.scatter_(1, y.view(-1, 1), 1)

print(y)
print(y_onehot)

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #3 'index'

In [3]:
worker = sy.VirtualWorker(hook, id="worker")
worker.clear_objects()
ptr = torch.tensor([1,2,3]).send(worker)
print(worker._objects) # Empty!

{}


In [4]:
t_x = th.tensor([-3.1, 1])
t_y = th.tensor([1.])
x = t_x.fix_prec().share(alice, bob, crypto_provider=james)
y = t_y.fix_prec()
z = (x * y)
z = z.get().float_prec()
assert (z == t_x * t_y).all()

mul tensor([1000])
try


In [8]:
t_x = th.tensor([-3.1, 1])
t_y = th.tensor([0., 2.1])
x = t_x.fix_prec().share(alice, bob, crypto_provider=james)
y = t_y.fix_prec()
z = (x * y)
z = z.get().float_prec()
print(z)
assert (z == t_x * t_y).all()

mul tensor([   0, 2100])
try
over
tensor([0.0000, 2.1000])


In [2]:
for i in range(10):
    x = th.tensor([0.00]).fix_prec().share(alice, bob, crypto_provider=james).child.child.child
    print(x.positive().get())

tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])


In [3]:
x = th.tensor([-3.1]).fix_prec().share(alice, bob, crypto_provider=james)
y = th.tensor([-3.1]).fix_prec().share(alice, bob, crypto_provider=james)

print((x * 2).get().float_prec())
assert (x >= y).get().float_prec()
assert (x <= y).get().float_prec()


tensor([-6.2000])


In [4]:
a = (
    torch.tensor([0.], requires_grad=True)
    .fix_prec()
    .share(alice, bob, crypto_provider=james)
)

r = (a *0)
print('virtual get', r.child.child.child.virtual_get())
r.get().float_prec()

virtual get tensor([0])


tensor([0.])

In [2]:
a = (
    torch.tensor([0.], requires_grad=True)
    .fix_prec()
    .share(alice, bob, crypto_provider=james)
)

a_ = a.child.child.child * 0
print('virtual get', a_.virtual_get())
r = (a_ / 2)
print('virtual get', r.virtual_get())
r.get()

virtual get tensor([0])
virtual get tensor([0])


tensor([0])

In [3]:
a = (
    torch.tensor([0.], requires_grad=True)
    .fix_prec()
    .share(alice, bob, crypto_provider=james)
)

a.child.child.child.locations

[<VirtualWorker id:alice #objects:2>, <VirtualWorker id:bob #objects:2>]

In [4]:
a = (
    torch.tensor([0.], requires_grad=True)
    .fix_prec()
    .share(alice, bob, crypto_provider=james)
)

r = (a *0)
print('virtual get', r.child.child.child.virtual_get())
r.get().float_prec()

TypeError: mul(): argument 'other' (position 2) must be Tensor, not dict

In [4]:
cmd = '__add__'
backward_one= False

a = (
    torch.tensor([[3.0, 2], [-1, 2]], requires_grad=True)
    .fix_prec()
    .share(alice, bob, crypto_provider=james)
)
b = (
    torch.tensor([[1.0, 2], [3, 2]], requires_grad=True)
    .fix_prec()
    .share(alice, bob, crypto_provider=james)
)

a = syft.AutogradTensor().on(a)
b = syft.AutogradTensor().on(b)

a_torch = torch.tensor([[3.0, 2], [-1, 2]], requires_grad=True)
b_torch = torch.tensor([[1.0, 2], [3, 2]], requires_grad=True)

c = getattr(a, cmd)(b)
c_torch = getattr(a_torch, cmd)(b_torch)

ones = torch.ones(c.shape).fix_prec().share(alice, bob, crypto_provider=james)
ones = syft.AutogradTensor().on(ones)
c.backward(ones if backward_one else None)
c_torch.backward(torch.ones(c_torch.shape))

a_ = a.grad.get().float_prec()
print(a_)
assert (a_ == a_torch.grad).all()
assert (b.grad.get().float_prec() == b_torch.grad).all()

AST get tensor([[1000, 1000],
        [1000, 1000]])
tensor([[1., 1.],
        [1., 1.]])
AST get tensor([[1000, 1000],
        [1000, 1000]])


In [ ]:
AutogradTensor>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:65088881866 -> alice:10153897986]
	-> (Wrapper)>[PointerTensor | me:25315616262 -> bob:47259652182]

In [5]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
torch.roll(x, torch.tensor(1))

TypeError: roll(): argument 'shifts' (position 2) must be tuple of ints, not Tensor

In [3]:
import syft as sy
import torch as th
hook = sy.TorchHook(th, is_client=False)
me = hook.local_worker
print(me._objects)  # {}
x = th.tensor([1, 2, 3])
print(me._objects) # {}

{}
{}


In [2]:
x11 = torch.tensor([-1, 2.0]).tag("input_data")
x12 = torch.tensor([1, -2.0]).tag("input_data2")
x21 = torch.tensor([-1, 2.0]).tag("input_data")
x22 = torch.tensor([1, -2.0]).tag("input_data2")

device_1 = sy.VirtualWorker(hook, id="device_1", data=(x11, x12))
device_2 = sy.VirtualWorker(hook, id="device_2", data=(x21, x22))

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 3)
        self.fc2 = nn.Linear(3, 2)

    @sy.method2plan
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=0)

net = Net()



In [3]:
net.send(device_1)
net.forward.send(device_1)
pointer_to_data = device_1.search("input_data")[0]
pointer_to_result = net(pointer_to_data)
pointer_to_result.get()

net.get()
net.forward.get()



build plan
>>> device_1
[[2, [1, [2, [[2, [[18, [b'torch.nn.functional.linear']], None, [2, [[11, [80204162882, 16586377296, 4449997337, None, [2]]], [11, [30720240863, 88388108859, b'me', None, [3, 2]]], [11, [36350848877, 68234091685, b'me', None, [3]]]]], [5, []]]], [3, [50133121151]]]]]], [2, [1, [2, [[2, [[18, [b'torch.nn.functional.relu']], None, [2, [[11, [53903414365, 50133121151, 4449997337, None, None]]]], [5, []]]], [3, [18130713138]]]]]], [2, [4, 50133121151]], [2, [1, [2, [[2, [[18, [b'torch.nn.functional.linear']], None, [2, [[11, [15709913566, 18130713138, 4449997337, None, None]], [11, [21127809241, 90525561739, b'me', None, [2, 3]]], [11, [19520590351, 89711292122, b'me', None, [2]]]]], [5, []]]], [3, [74143182466]]]]]], [2, [4, 18130713138]], [2, [1, [2, [[2, [[18, [b'torch.nn.functional.log_softmax']], None, [2, [[11, [43998315164, 74143182466, 4449997337, None, None]]]], [5, [[[18, [b'dim']], 0]]]]], [3, [17113956850]]]]]], [2, [4, 74143182466]]]

['me', 'device_1']

<Plan forward id:4449997337 owner:me built>

In [4]:
id(device_1._objects[1159910918])

4461229448

In [4]:
[[2, [1, [2, [[2, [[18, ['torch.nn.functional.linear']], None, [2, [[11, [78502130028, 4479807089, 2886041565, None, [2]]], [11, [97894262498, 48189120854, 'me', None, [3, 2]]], [11, [64809977208, 98367448715, 'me', None, [3]]]]], [5, []]]], [3, [94772411841]]]]]], [2, [1, [2, [[2, [[18, ['torch.nn.functional.relu']], None, [2, [[11, [53701961874, 94772411841, 2886041565, None, None]]]], [5, []]]], [3, [49524943901]]]]]], [2, [4, 94772411841]], [2, [1, [2, [[2, [[18, ['torch.nn.functional.linear']], None, [2, [[11, [79493817385, 49524943901, 2886041565, None, None]], [11, [65422314321, 55416654853, 'me', None, [2, 3]]], [11, [45510336156, 52153300180, 'me', None, [2]]]]], [5, []]]], [3, [90421923737]]]]]], [2, [4, 49524943901]], [2, [1, [2, [[2, [[18, ['torch.nn.functional.log_softmax']], None, [2, [[11, [43552716600, 90421923737, 2886041565, None, None]]]], [5, [[[18, ['dim']], 0]]]]], [3, [88778121339]]]]]], [2, [4, 90421923737]]][0]

[2,
 [1,
  [2,
   [[2,
     [[18, ['torch.nn.functional.linear']],
      None,
      [2,
       [[11, [78502130028, 4479807089, 2886041565, None, [2]]],
        [11, [97894262498, 48189120854, 'me', None, [3, 2]]],
        [11, [64809977208, 98367448715, 'me', None, [3]]]]],
      [5, []]]],
    [3, [94772411841]]]]]]

In [3]:
net.send(device_2)
net.forward.send(device_2)
pointer_to_data = device_2.search("input_data")[0]
pointer_to_result = net(pointer_to_data)
pointer_to_result.get()

[4, 2, 3]

In [1]:
import numpy as np

In [2]:
np.random.randint(0, 4, (2**28, ))

array([0, 2, 0, ..., 3, 0, 0])

In [10]:
2**25

33554432

In [5]:
o = o.move(bob)
print(o)

(Wrapper)>[PointerTensor | me:55442188011 -> bob:55442188011]


In [3]:
o.send(bob)

(Wrapper)>[PointerTensor | me:97242093492 -> bob:18151069911]

In [2]:
F.relu

<function torch.nn.functional.relu(input, inplace=False)>

In [3]:
x = F.relu(th.tensor([3.1,-3.2, 3.3]).fix_prec().share(alice, bob, crypto_provider=james))

In [4]:
x

(Wrapper)>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:75243944670 -> alice:68891807964]
	-> (Wrapper)>[PointerTensor | me:57620238793 -> bob:53277847274]
	*crypto provider: jason*

In [10]:
5&5

5

In [2]:
x = th.tensor([3.1]).fix_prec().share(alice, bob, crypto_provider=james)
y = th.tensor([3.1]).fix_prec().share(alice, bob, crypto_provider=james)

assert (x >= y).get().float_prec()

RuntimeError: Overflow when unpacking long

In [2]:
x11 = torch.tensor([-1, 2.0]).tag("input_data")
x12 = torch.tensor([1, -2.0]).tag("input_data2")
x21 = torch.tensor([-1, 2.0]).tag("input_data")
x22 = torch.tensor([1, -2.0]).tag("input_data2")

device_1 = sy.VirtualWorker(hook, id="device_1", data=(x11, x12))
device_2 = sy.VirtualWorker(hook, id="device_2", data=(x21, x22))

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 3)
        self.fc2 = nn.Linear(3, 2)

    @sy.method2plan
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.log_softmax(x, dim=0)

net = Net()

net.send(device_1)
net.forward.send(device_1)
pointer_to_data = device_1.search("input_data")[0]
print(pointer_to_data)
pointer_to_result = net(pointer_to_data)
pointer_to_result.get()

net.get()
net.forward.get()

net.send(device_2)
net.forward.send(device_2)
pointer_to_data = device_2.search("input_data2")[0]
pointer_to_result = net(pointer_to_data)
pointer_to_result.get()

(Wrapper)>[PointerTensor | me:98021693792 -> device_1:89114370746]
	Tags: input_data 
	Shape: torch.Size([2])
me
device_1
sendinf command execute plan to  device_1
<VirtualWorker id:device_1 #tensors:7> running
[(Wrapper)>tensor([-1.,  2.])
	Tags: input_data 
	Shape: torch.Size([2])]
[[2, [1, [2, [[2, ['torch.nn.functional.linear', None, [2, [[11, [34685389567, 98021693792, 8972123230, None, [2]]], [11, [54926661013, 55764910497, 'device_1', None, [3, 2]]], [11, [52691138892, 8732221862, 'device_1', None, [3]]]]], [5, {}]]], [3, [23751204510]]]]]], [2, [1, [2, [[2, ['torch.nn.functional.relu', None, [2, [[11, [77278034551, 23751204510, 8972123230, None, None]]]], [5, {}]]], [3, [40232338219]]]]]], [2, [4, 23751204510]], [2, [1, [2, [[2, ['torch.nn.functional.linear', None, [2, [[11, [8601957778, 40232338219, 8972123230, None, None]], [11, [30138887788, 1717419017, 'device_1', None, [2, 3]]], [11, [60707083850, 20286560557, 'device_1', None, [2]]]]], [5, {}]]], [3, [31021262519]]]]]], [

tensor([-0.6225, -0.7691], requires_grad=True)

## Test tensor mm fix precision

In [16]:
weight = th.tensor([[1., 1], [-1., -1]])
bias = th.tensor([0.])
x = th.ones(1, 2) * -1
F.linear(x, weight, bias)

tensor([[-2.,  2.]])

In [5]:
weight = weight.fix_prec()
bias = bias.fix_prec()
x = x.fix_prec()

In [6]:
F.linear(x, weight, bias).float_precision()

tensor([[      4294965294000, 9223363438332253218]])
tensor([[-2000,  2000]])


tensor([[-2.,  2.]])

In [24]:
(weight * x).float_precision()

tensor([[-1.0000e+00, -1.0000e+00],
        [-7.5806e+05, -7.5806e+05]])

In [14]:
F = 2147483647
x = (F - 1000)*(2000)
x == 2000 * F - 2*10**6
x % F

2145483647

In [3]:
x = th.tensor([2]).fix_prec()
y = th.tensor([-1]).fix_prec()
(y * x).float_precision()

tensor([4294965294000])
tensor([-2000])


tensor([-2.])

In [7]:
2147482647, x.child.field

(2147482647, 2147483647)

In [12]:
(2147482647 * 2000) % F


2145483647

In [ ]:
23622309117000

In [7]:
x = th.tensor([3.1, 3.0])#.fix_prec()
lin = nn.Linear(2, 1)

In [8]:
lin(x)

tensor([0.3598], grad_fn=<AddBackward0>)

In [9]:
lin.fix_precision()

Linear(in_features=2, out_features=1, bias=True)

In [10]:
lin.forward(x.fix_prec())

In [3]:
x = th.tensor([3.1]).fix_prec().share(alice, bob, crypto_provider=james)
y = th.tensor([3.1]).fix_prec().share(alice, bob, crypto_provider=james)

#(x >= y).get().float_prec()
x * y

(Wrapper)>FixedPrecisionTensor>(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:78689909304 -> alice:94324209699]
	-> (Wrapper)>[PointerTensor | me:42666297638 -> bob:30462102307]
	*crypto provider: jason*

In [3]:
torch.matmul(ast, mpt)

(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:42505572255 -> alice:56619219891]
	-> (Wrapper)>[PointerTensor | me:68637354458 -> bob:76120546367]
	*crypto provider: jason*

In [4]:
m = torch.tensor([[1, 2], [3, 4.0]])
x = m.fix_prec().share(bob, alice, crypto_provider=james)
y = (x * x).get().float_prec()
y

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [5]:
m @ m

tensor([[ 7., 10.],
        [15., 22.]])

In [6]:
x = th.tensor([[2, 3], [2, 3]]).share(alice, bob, crypto_provider=james)
y = th.tensor([[-3, 1], [1, 1]]).share(alice, bob, crypto_provider=james)
z = th.tensor([2, 2]).send(alice, bob)
z2 = th.tensor([1, 3]).send(alice, bob)

In [7]:
(x @ y).get()

tensor([[-3,  5],
        [-3,  5]])

In [8]:
x = th.tensor([3]).share(alice, bob, crypto_provider=james)
y = th.tensor([3])
x * 2

(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:6337965245 -> alice:84547335044]
	-> (Wrapper)>[PointerTensor | me:60795715715 -> bob:89706847120]
	*crypto provider: jason*

In [11]:
th.tensor([[2, 3], [2, 3]]) @ th.tensor([[-3, 1], [1, 1]])

tensor([[-3,  5],
        [-3,  5]])

In [6]:
for i in range(6):
    x = th.randint(1, 10, (10**i,)).share(alice, bob, crypto_provider=james)
    print(x.shape)
    y = th.randint(1, 10, (10**i,)).share(alice, bob, crypto_provider=james)
    %time r = x > y

torch.Size([1])
[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:24855607749 -> alice:1057659768]
	-> (Wrapper)>[PointerTensor | me:13661638499 -> bob:69453174098]
	*crypto provider: jason*
CPU times: user 81.1 ms, sys: 2.23 ms, total: 83.3 ms
Wall time: 83.1 ms
torch.Size([10])
[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:77661757588 -> alice:22643555129]
	-> (Wrapper)>[PointerTensor | me:35853767685 -> bob:62673183073]
	*crypto provider: jason*
CPU times: user 71.8 ms, sys: 1.13 ms, total: 72.9 ms
Wall time: 72.9 ms
torch.Size([100])
[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:66819799000 -> alice:15871048243]
	-> (Wrapper)>[PointerTensor | me:31645790716 -> bob:35361767163]
	*crypto provider: jason*
CPU times: user 84.9 ms, sys: 2.09 ms, total: 87 ms
Wall time: 87.2 ms
torch.Size([1000])
[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:71250269479 -> alice:62907836364]
	-> (Wrapper)>[PointerTensor | me:11391544990 -> bob:12008958471]
	*cr

In [8]:
14 / 100 

0.14

In [10]:
x = th.tensor([1, 2, 3])
x.lt(x)

tensor([0, 0, 0], dtype=torch.uint8)

In [9]:
x_bit = th.tensor([1, 2, 3])
x_bit[..., -1:]

tensor([3])

In [3]:
x = th.tensor([2]).share(alice, bob, crypto_provider=james)
x > x

[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:4414991801 -> alice:69420192374]
	-> (Wrapper)>[PointerTensor | me:75895581014 -> bob:15285416840]
	*crypto provider: jason*


(Wrapper)>[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:7760512957 -> bob:72004379942]
	-> (Wrapper)>[PointerTensor | me:75392936166 -> alice:91843606936]
	*crypto provider: jason*

In [5]:
y = ptr.remote_get()

In [6]:
y.get()

tensor([2])

In [4]:
james._objects

{98751843098: (Wrapper)>[AdditiveSharingTensor]
 	-> (Wrapper)>[PointerTensor | jason:58805294149 -> alice:30809711388]
 	-> (Wrapper)>[PointerTensor | jason:12700267518 -> bob:1710599976]
 	*crypto provider: jason*}

In [6]:
james._objects

{98751843098: tensor([2]),
 30809711388: tensor([947841480]),
 1710599976: tensor([-947841478])}

In [4]:
location = ptr.child.location
print(ptr.child.id_at_location)
ptr.owner.send_command(message=("get", ptr.child, (), {}), recipient=location)

38057402347


[PointerTensor | me:39630348077 -> jason:57767395295]

In [5]:
james._objects

{38057402347: tensor([]),
 50643483076: tensor([1947581635]),
 25764809366: tensor([-1947581633]),
 57767395295: tensor([2])}

In [8]:
james._objects

{64777347010: (Wrapper)>[AdditiveSharingTensor]
 	-> (Wrapper)>[PointerTensor | jason:8534623488 -> bob:25618355259]
 	-> (Wrapper)>[PointerTensor | jason:68426588058 -> alice:37333954348]
 	*crypto provider: jason*, 95442763981: (Wrapper)>[AdditiveSharingTensor]
 	-> (Wrapper)>[PointerTensor | jason:40205406926 -> alice:97592259626]
 	-> (Wrapper)>[PointerTensor | jason:42866938053 -> bob:2843874393]
 	*crypto provider: jason*}

In [3]:
x = th.tensor([5.1]).fix_prec().share(alice, bob, crypto_provider=james)
y = th.tensor([3.1]).fix_prec().share(alice, bob, crypto_provider=james)

(x > y).get().float_prec()

[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:10695844523 -> alice:52953266289]
	-> (Wrapper)>[PointerTensor | me:89334418864 -> bob:47304247206]
	*crypto provider: jason*


tensor([1.])

In [8]:
x = torch.tensor([[1, 2], [3, 4]]).share(alice, bob, crypto_provider=james)
x == x

[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:75650674461 -> bob:8861822167]
	-> (Wrapper)>[PointerTensor | me:59382629763 -> alice:75805147310]
	*crypto provider: jason*
31
[MultiPointerTensor]
	-> (Wrapper)>[PointerTensor | me:21246606597 -> alice:35228744949]
	-> (Wrapper)>[PointerTensor | me:31529712843 -> bob:41034875915]
<class 'syft.frameworks.torch.tensors.interpreters.multi_pointer.MultiPointerTensor'>
hooky
(slice(None, None, None), {'alice': (Wrapper)>[PointerTensor | me:21246606597 -> alice:35228744949], 'bob': (Wrapper)>[PointerTensor | me:31529712843 -> bob:41034875915]})


RuntimeError: shape '[2]' is invalid for input of size 4

In [31]:
c = torch.tensor([2, 4, 3, 0, 9, 8, 1, 5, 7, 6])

In [37]:
perm = torch.randperm(len(c))
masked = torch.tensor(list(range(10))) + 1
print(perm)
print(masked)
masked[perm, ]

tensor([4, 2, 0, 7, 6, 8, 1, 9, 5, 3])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


tensor([ 5,  3,  1,  8,  7,  9,  2, 10,  6,  4])

In [7]:
x = torch.tensor([[1, 2], [3, 4]]).send(alice, bob)
y = torch.tensor([[1, 2], [3, 4]]).share(alice, bob)
x.add(y)

(Wrapper)>[MultiPointerTensor]
	-> (Wrapper)>[PointerTensor | me:10591114494 -> alice:35215791293]
	-> (Wrapper)>[PointerTensor | me:82691299508 -> bob:68787080723]

In [11]:
torch.randint(3, 5, (3,))

tensor([4, 3, 4])

In [4]:
F.linear(tensor, weight).float_prec()

tensor([[ 5., 11.],
        [11., 25.]])

In [3]:
x = torch.tensor([2.113]).fix_prec(precision_fractional=3)

y = torch.mul(x, x)

y = y.float_prec()
y

ok 3


tensor([4.4640])

In [4]:
x = torch.tensor([2.113]).fix_prec(precision_fractional=2)

y = torch.mul(x, x)

assert y.child.child == torch.LongTensor([445])

y = y.float_prec()
y

ok 2


tensor([4.4500])

In [8]:
y = torch.mul(x, x)
print(y.child.precision_fractional)
y.float_prec()

2


tensor([4.4500])

In [4]:
x = th.tensor([2.1]).fix_prec().share(alice, bob, crypto_provider=james)
y = th.tensor([3.1]).fix_prec().share(alice, bob, crypto_provider=james)

((x >= y).get().float_prec())

<VirtualWorker id:me #tensors:0>
<VirtualWorker id:me #tensors:0>


tensor([0.])

In [11]:
x = th.tensor([3.1]).fix_prec().share(alice, bob, crypto_provider=james)
y = th.tensor([2.1]).fix_prec().share(alice, bob, crypto_provider=james)

In [12]:
assert not (x == y).get().float_prec()

kkooky


In [10]:
x.child.child.child

[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:89817268848 -> alice:94785363938]
	-> (Wrapper)>[PointerTensor | me:82178043197 -> bob:46085121388]
	*crypto provider: jason*

In [7]:
(x.child.child.child == y.child.child.child).get()

tensor([1])

In [8]:
(x.child >= y.child).get().float_prec()

tensor([1.])

In [11]:
r = torch.eq(x.child, y.child)

In [13]:
r.get()

(Wrapper)>FixedPrecisionTensor>tensor([1])

In [3]:
x.child.child.child.child

{'alice': (Wrapper)>[PointerTensor | me:98921816101 -> alice:42485618237],
 'bob': (Wrapper)>[PointerTensor | me:72209472099 -> bob:43441020999]}

In [14]:
r = x.relu()

a tensor([ 1, -3])
relu_deriv(a tensor([1, 0])


In [15]:
r.get()

tensor([1, 0])

### Real setting to test private_compare

In [3]:
x_sh = th.tensor([0,0,0,0])#randoms shit
x_bit_sh = decompose(th.tensor([4, 4, 4, 4])).share(alice, bob, crypto_provider=jason).child
r = th.tensor([4, 4, 4, 4]).send(alice, bob).child
BETA = (torch.rand(x_sh.shape) > 0.5).long().send(bob, alice).child
# BETA = torch.zeros(x_sh.shape).long().send(bob, alice).child
j0 = torch.zeros(x_bit_sh.shape).long().send(bob)
j1 = torch.ones(x_bit_sh.shape).long().send(alice)
j = syft.MultiPointerTensor(children=[j0, j1])

In [4]:
beta_p_x_gt_r = private_compare(x_bit_sh, r, BETA=BETA, j=j, alice=alice, bob=bob).long()
beta = BETA.get()[0]
print(beta_p_x_gt_r, beta)
x_gt_r = beta_p_x_gt_r + beta
print(x_gt_r)
print(x_gt_r % 2)

tensor([1, 0, 0, 1]) tensor([0, 1, 1, 0])
tensor([1, 1, 1, 1])
tensor([1, 1, 1, 1])


### Real setting to test  xor implem

In [13]:
r = decompose(th.tensor([3])).send(alice, bob).child
x_bit_sh = decompose(th.tensor([23])).share(alice, bob, crypto_provider=jason).child
j0 = torch.zeros(x_bit_sh.shape).long().send(bob)
j1 = torch.ones(x_bit_sh.shape).long().send(alice)
j = syft.MultiPointerTensor(children=[j0, j1])
w = (j * r) + x_bit_sh - (2 * x_bit_sh * r)

r_real = r.virtual_get()[0]
x_real = x_bit_sh.virtual_get()
w_real = r_real + x_real - 2 * r_real * x_real
assert (w.virtual_get() == w_real).all()

In [14]:
x = th.tensor([1, 3]).share(alice, bob, crypto_provider=jason).child
r = th.tensor([7, 5]).send(alice, bob).child
print(x)
print(r)

[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:13862762346 -> alice:70903314975]
	-> (Wrapper)>[PointerTensor | me:73546589887 -> bob:92466459676]
	*crypto provider: jason*
[MultiPointerTensor]
	-> (Wrapper)>[PointerTensor | me:57174799501 -> alice:44475236354]
	-> (Wrapper)>[PointerTensor | me:86861928750 -> bob:22056709962]


In [15]:
th.tensor([1., 2, -0.1]).positive()

AttributeError: 'Tensor' object has no attribute 'positive'

In [8]:
x = th.tensor([1., 2, 0.1]).fix_prec().share(alice, bob, crypto_provider=jason)
x.child.child.child.field

2147483647

In [11]:
sx = x.child.child.child
#sx.owner = sy.hook.local_worker
sx

[AdditiveSharingTensor]
	-> (Wrapper)>[PointerTensor | me:53731605998 -> alice:42292714001]
	-> (Wrapper)>[PointerTensor | me:90110718740 -> bob:53089957619]
	*crypto provider: jason*

In [12]:
relu(sx).get()

a tensor([1000, 2000,  100])
relu_deriv(a tensor([1, 1, 1])


tensor([1000, 2000,  100])

In [6]:
x = torch.LongTensor(th.Size([6, 2])).random_(9 - 1)
x

tensor([[2, 2],
        [6, 1],
        [5, 5],
        [1, 7],
        [6, 5],
        [6, 0]])

In [7]:
x = torch.tensor([0, 0], dtype=torch.uint8)

In [10]:
x.long().dtype

torch.int64

In [ ]:
j0 = torch.zeros(torch.Size([5])).long().send(bob)
j1 = torch.ones(torch.Size([5])).long().send(alice)
j = syft.AdditiveSharingTensor().on(
    {bob: j0, alice: j1},
    wrap = False
)

In [ ]:
j

In [ ]:
x = th.tensor([1., 2]).fix_prec().share(alice, bob)

In [ ]:
torch.add(x, x)